#  Disclaimer
#
#  This work (specification and/or software implementation) and the material
#  contained in it, as released by AUTOSAR, is for the purpose of information
#  only. AUTOSAR and the companies that have contributed to it shall not be
#  liable for any use of the work.
#
#  The material contained in this work is protected by copyright and other
#  types of intellectual property rights. The commercial exploitation of the
#  material contained in this work requires a license to such intellectual
#  property rights.
#
#  This work may be utilized or reproduced without any modification, in any
#  form or by any means, for informational purposes only. For any other
#  purpose, no part of the work may be utilized or reproduced, in any form
#  or by any means, without permission in writing from the publisher.
#
#  The work has been developed for automotive applications only. It has
#  neither been developed, nor tested for non-automotive applications.
#
#  The word AUTOSAR and the AUTOSAR logo are registered trademarks.
#  --------------------------------------------------------------------------

# A file defining further services that are used during development (or possibly demonstration)
# That are intended to interact with the devcontainer
# E.g. a service realizing a second machine that is the communication counterpart of the machine under development.


networks:
  # The network used to connect different machines during development
  shared_network:
    name: capi_shared_network


services:

# A service to play the counterpart in the demo setup
  capi_demo:
    container_name: capi_demo
    build:
      context: ..
      dockerfile: demo/Dockerfile
      additional_contexts:
        capi_devcontainer: docker-image://capi-devcontainer-image:latest
    stdin_open: true
    tty: true
    networks:
      - shared_network
    cap_add:
      - SYS_PTRACE
